language: generic

services:
  - docker

install:
  - docker build -t jctiru/lnshop-frontend .

script:
  - docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION -e S3_BUCKET=$S3_BUCKET jctiru/lnshop-frontend

branches:
  only:
    - master
