export const OrderActionTypes = {
  CREATE_ORDER_START: "CREATE_ORDER_START",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAILURE: "CREATE_ORDER_FAILURE",
  CRUD_ORDER_STATUS_RESET: "CRUD_ORDER_STATUS_RESET"
};
