export const NovelActionTypes = {
  GET_GENRES_START: "GET_GENRES_START",
  GET_GENRES_SUCCESS: "GET_GENRES_SUCCESS",
  GET_GENRES_FAILURE: "GET_GENRES_FAILURE",
  GET_NOVELS_START: "GET_NOVELS_START",
  GET_NOVELS_SUCCESS: "GET_NOVELS_SUCCESS",
  GET_NOVELS_FAILURE: "GET_NOVELS_FAILURE",
  CREATE_NOVEL_START: "CREATE_NOVEL_START",
  CREATE_NOVEL_SUCCESS: "CREATE_NOVEL_SUCCESS",
  CREATE_NOVEL_FAILURE: "CREATE_NOVEL_FAILURE"
};
